CREATE TABLE locations (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
address TEXT,
total_slots INTEGER NOT NULL
);


CREATE TABLE slots (
id SERIAL PRIMARY KEY,
location_id INTEGER REFERENCES locations(id) ON DELETE CASCADE,
start_time TIMESTAMP NOT NULL,
end_time TIMESTAMP NOT NULL,
is_booked BOOLEAN DEFAULT FALSE
);


CREATE TABLE bookings (
id SERIAL PRIMARY KEY,
slot_id INTEGER REFERENCES slots(id) ON DELETE CASCADE,
user_id UUID,
status VARCHAR(20) CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED')),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
expires_at TIMESTAMP
);